### ISSUE TITLE
Problem with running it

### ISSUE THREAD

**Issue by CottonEyeJ0e** [thomas-crane/nrelay#7]
First time it said something about not being able to update packages, now it just says Couldn't load acc-config.json
what do

**Comment by CottonEyeJ0e** [comment]
It said "The packet updater is manually disabled" or something

**Comment by Gravitir314** [comment]
Thank you for [trying] to use nrelay!
---
### First i highly recommend you to use version from *dev* branch.
Because now it's newest version with enabled auto-updating.
To change branch go to main window and find tab with text "2 branches", next click on this tab.
After choose *dev* branch from list.

Images:
[Main window](http://prntscr.com/j9b4og)
[Branch list](http://prntscr.com/j9b5oy)
### If you have problems with acc-config, then if you use over then 1 account, make sure you add commas after closing brackets, like:
```
{
    "buildVersion": "X24.0.0",
    "accounts": [
        {
                "alias": "EUEast",
                "guid": "firstmail@gmail.com",
                "password": "firstpassword",
                "serverPref": "EUEast"
        }, //add commas
	{
		"alias": "USSouth",
                "guid": "secondmail@gmail.com",
                "password": "secondpassword",
                "serverPref": "USSouth"
	}, //same
	{
		"alias": "USEast2",
                "guid": "thirdmail@gmail.com",
                "password": "thirdpassword",
                "serverPref": "USEast2"
	} //on last account do not add commas
    ]
}
```

**Comment by thomas-crane** [comment]
I'm going to assume you managed to get nrelay running since there haven't been any more comments on this issue.

Please re-open this issue if you are still having troubles.
